apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: monitoring-apps
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: https://github.com/catterad/helm_home_monitoring.git
      revision: main
      directories:
        - path: charts/*
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/catterad/helm_home_monitoring.git
        targetRevision: main
        path: '{{path}}'
        helm:
          releaseName: '{{path.basename}}'
          valueFiles:
            - values.yaml     # automatically picks up values.yaml from each /chart/app-name/
      destination:
        server: https://kubernetes.default.svc
        namespace: monitoring
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - createNamespace=true
