```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-self-managed
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/refresh: hard
spec:
  project: default
  source:
    repoURL: https://github.com/catterad/argocd_home_config.git
    targetRevision: HEAD
    path: manifests/argocd
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - RespectIgnoreDifferences=true
      - ApplyOutOfSyncOnly=true
    managedNamespaceMetadata:
      annotations:
        argocd.argoproj.io/compare-options: IgnoreExtraneous

  ignoreDifferences:
    - group: apps
      kind: Deployment
      name: argocd-server
      namespace: argocd
      jsonPointers:
        # Ignore K8s-managed metadata
        - /metadata/annotations
        - /metadata/generation
        - /status
        # Ignore runtime defaults
        - /spec/replicas
        - /spec/template/spec/containers/0/livenessProbe
        - /spec/template/spec/containers/0/readinessProbe
        - /spec/template/spec/containers/0/ports
        - /spec/template/spec/containers/0/resources
        - /spec/template/spec/containers/0/terminationMessagePath
        - /spec/template/spec/containers/0/terminationMessagePolicy
        - /spec/template/spec/securityContext
        - /spec/template/spec/volumes

    - kind: Service
      namespace: argocd
      jsonPointers:
        - /spec/clusterIP
        - /spec/clusterIPs
```
