apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-self-managed
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/refresh: hard
spec:
  project: default
  source:
    repoURL: https://github.com/catterad/argocd_home_config.git
    targetRevision: HEAD
    path: manifests/argocd
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - RespectIgnoreDifferences=true
      - ApplyOutOfSyncOnly=true
    managedNamespaceMetadata:
      annotations:
        argocd.argoproj.io/compare-options: IgnoreExtraneous

  ignoreDifferences:        # <-- moved here, under spec
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas
        - /metadata/annotations
        - /metadata/generation
        - /status
    - kind: Service
      jsonPointers:
        - /spec/clusterIP
        - /spec/clusterIPs
