apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-self-managed
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/refresh: hard
spec:
  project: default
  source:
    repoURL: https://github.com/catterad/argocd_home_config.git
    targetRevision: HEAD
    path: manifests/argocd
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - RespectIgnoreDifferences=true
      - ApplyOutOfSyncOnly=true
    managedNamespaceMetadata:
      annotations:
        argocd.argoproj.io/compare-options: IgnoreExtraneous

ignoreDifferences:
   - group: apps
     kind: Deployment
     name: argocd-server
     namespace: argocd
     jsonPointers:
       # Ignore ArgoCD-injected annotations
       - /metadata/annotations
       # Ignore generation drift
       - /metadata/generation
       # Ignore runtime-only status
       - /status
       # Ignore replica count differences
       - /spec/replicas
       # Ignore probe defaults
       - /spec/template/spec/containers/0/livenessProbe
       - /spec/template/spec/containers/0/readinessProbe
       # Ignore protocol defaults on container ports
       - /spec/template/spec/containers/0/ports
       # Ignore runtime defaults for volumes
       - /spec/template/spec/volumes

